fixes #2533 if use the prepend_search_result will lead to error:
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.alibaba.cloud.ai.dashscope.api.DashScopeApi$TokenUsage.inputTokens()" is null
at com.alibaba.cloud.ai.dashscope.chat.DashScopeChatModel.getDefaultUsage(DashScopeChatModel.java:398) ~[spring-ai-alibaba-core-1.0.0.3.jar:1.0.0.3]